### PR TITLE
Add dynamoDB examples

### PR DESCRIPTION
**Pull request by jrichard8**
Add some example of use of dynamoDB with AWS SDK v2

### CODE REVIEW

**Comment by skotambkar** [comment]
@Doug-AWS can you take a look at this and see if these should be added to our V2 examples repo?

**Review by jasdel — CHANGES_REQUESTED** [review]
Examples look good, we'll want to update the dependencies to be SDK's latest versions, and update the examples to use the SDK's ddb attribute value (un)marshalers.

**Comment by jrichard8** [comment]
I think I made requested changes, waiting for review.

**Comment by jrichard8** [comment]
@jasdel can you take a look ?

**Review by jasdel — APPROVED** [review]
Thanks for taking the time to create these examples. I've kicked off the CI Actions, and the changes look good. When these pass we should be able to merge in these example modules.

**Pull request merged**
