### PR TITLE
example/service/sagemaker: Add create training job example

### PR DESCRIPTION
**Pull request by goswamig**
For changes to files under the `/model/` folder, and manual edits to autogenerated code (e.g. `/service/s3/api.go`) please create an Issue instead of a PR for those type of changes.

If there is an existing bug or feature this PR is answers please reference it here.

### CODE REVIEW

**Comment by gautamkmr** [comment]
As par Json comments each files need to be in separate directory in order for build to pass.  He also suggested to add a README per file

**Comment by gautamkmr** [comment]
@jasdel  how can I see why the Codebuild is failing for this ?

**Comment by gautamkmr** [comment]
@jasdel  would you please review this ?

**Comment by jasdel** [comment]
Thanks for creating the SageMaker example @gautamkmr. They look good, I made a few formatting updates to the example, and will get them merged in.

**Pull request merged**
