### PR TITLE
i1494 passing opts to attributevalue marshalling

### LINKED ISSUE #1494: Pass KeyTag to dynamo attributevalue marshalling
### Describe the feature

As a AWS SDK go v2 user, I want to be able to set a custom `KeyTag` on `attributevalue.MarshalMap`, so I can keep the compatibility with previous v1 SDK.

### Is your Feature Request related to a problem?

Currently the `attributevalue.MarshalMap` doesn't accept the Encoder options, even though it is possible without breaking changes.

By default, `KeyTag` is set to `dynamoav`. Passing the Encoder options will allow setting up a KeyTag like `json`.

### Proposed Solution

_No response_

### Describe alternatives you've considered

_No response_

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Go SDK version used

v2

### Go version used

1.16

### PR DESCRIPTION
**Pull request by radutopala**
Fixes #1494

### CODE REVIEW

**Review by jasdel — CHANGES_REQUESTED** [review]
Thanks for taking the time to create this PR @radutopala. Modifing the signatures of the `Marshal` methods would be a breaking change, and we could not release it. 

Alternatively new `Marshal` methods could be defined with different names, e.g. `MarshalWithOptions` to take the functional options.

Also we'd probably want similar new functions for the `Unmarshal` set of functions.

**Comment by radutopala** [comment]
Adding `optFns ...func(*EncoderOptions)` as a variadic arg means no breaking changes, one can call Marshall with or without passing any optFns. But if I'm missing something, please let me know.

**Comment by jasdel** [comment]
Thanks for the feedback. Adding a variadic arg to a function call will not break existing callers, but since in Go functions can be types and variables, any application that creates a variable or struct member type matching the `Marshal` function signature would break if variadic arg were added.

https://go.dev/play/p/c4yT8-DsHo9

**Comment by radutopala** [comment]
@jasdel it's an extreme edge case, wondering who'd use this pattern with this specific func. But ok, better safe! I'll push some changes.

**Comment by radutopala** [comment]
@jasdel branch updated, please CR / provide next steps.

**Review by jasdel — APPROVED** [review]
Thanks for taking the time to put this PR together, and make the requested updates. I've added changelog notes to the PR. We'll get this update merged in and released in the SDK's next update.

**Pull request merged**
