### PR TITLE
s3manager: ensure parity between UploadInput and PutObjectInput

### LINKED ISSUE #88: s3manager: Uploader panics when custom metadata is provided
### Version of AWS SDK for Go?

Current master as of 2018-01-10: 14d1593063ec4c5c47f94db30a57d10e8c044f9a

### Version of Go (`go version`)?

```
% go version
go version devel +9044f018ec Tue Jan 9 01:53:38 2018 +0000 darwin/amd64
```

### What issue did you see?

s3manager.Uploader panics when uploading an object with custom metadata.

### Steps to reproduce

Code (make sure to set the bucket name): https://play.golang.org/p/l1nWAdGf_qT

Output:

```
% go run upload.go
panic: reflect.Set: value of type map[string]*string is not assignable to type map[string]string

goroutine 1 [running]:
reflect.Value.assignTo(0x139e400, 0xc4206c4030, 0x15, 0x14342cc, 0xb, 0x139ebe0, 0x0, 0x139e400, 0xc4206c4030, 0x15)
	/Users/fsouza/.gimme/versions/go/src/reflect/value.go:2235 +0x41d
reflect.Value.Set(0x139ebe0, 0xc4206c6090, 0x195, 0x139e400, 0xc4206c4030, 0x15)
	/Users/fsouza/.gimme/versions/go/src/reflect/value.go:1373 +0xa4
github.com/aws/aws-sdk-go-v2/internal/awsutil.rcopy(0x139ebe0, 0xc4206c6090, 0x195, 0x139e400, 0xc42012c230, 0x195, 0xc4206c6000)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:97 +0xc3f
github.com/aws/aws-sdk-go-v2/internal/awsutil.rcopy(0x142a820, 0xc4206c6000, 0x199, 0x14287a0, 0xc42012c1c0, 0x199, 0x1)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:78 +0x261
github.com/aws/aws-sdk-go-v2/internal/awsutil.rcopy(0x14194a0, 0xc4206c6000, 0x16, 0x1373820, 0xc42012c1c0, 0x16, 0x101)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:68 +0x8e7
github.com/aws/aws-sdk-go-v2/internal/awsutil.Copy(0x14194a0, 0xc4206c6000, 0x1373820, 0xc42012c1c0)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/internal/awsutil/copy.go:21 +0xb9
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.(*uploader).singlePart(0xc420177ea0, 0x14a50c0, 0xc4206c4000, 0x1, 0x14a39e0, 0xc420010050)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:558 +0x65
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.(*uploader).upload(0xc420177ea0, 0x0, 0x0, 0x0)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:458 +0x537
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.Uploader.UploadWithContext(0x500000, 0x5, 0x0, 0x2710, 0x14aca40, 0xc420011260, 0x0, 0x0, 0x0, 0x1c08210, ...)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:376 +0x184
github.com/aws/aws-sdk-go-v2/service/s3/s3manager.Uploader.Upload(0x500000, 0x5, 0x0, 0x2710, 0x14aca40, 0xc420011260, 0x0, 0x0, 0x0, 0xc42012c1c0, ...)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload.go:347 +0xc4
main.main()
	/Users/fsouza/upload.go:17 +0x41b
exit status 2
```

### PR DESCRIPTION
**Pull request by fsouza**
Fix #88.

### CODE REVIEW

**Comment by jasdel** [comment]
Thanks for posting this PR @fsouza, looks like there are actually a couple fields that need to be updated. the [s3manager's tests](https://github.com/aws/aws-sdk-go-v2/blob/master/service/s3/s3manager/upload_test.go#L768) are supposed to catch this, but it looks like these test ignore the field's type, and only compare name.

would you mind also updating the `upload_test.go` tests to correctly check against the type. This will show that the `StorageClass`, `ACL`, and `RequestPayer` fields are also need to be updated.

```diff
 var emptyList = []string{}

 func val(i interface{}, s string) interface{} {
-       fmt.Println("INNER", i)
        v, err := awsutil.ValuesAtPath(i, s)
        if err != nil || len(v) == 0 {
                return nil
@@ -772,7 +771,12 @@ func TestUploadInputS3PutObjectInputPairity(t *testing.T) {
        bOnly := []string{}

        for k, c := range matchings {
-               if c == 1 && k != "ContentLength" {
+               if strings.HasPrefix(k, "Body") || strings.HasPrefix(k, "ContentLength") {
+                       // Ignored fields
+                       continue
+               }
+
+               if c == 1 {
                        aOnly = append(aOnly, k)
                } else if c == 2 {
                        bOnly = append(bOnly, k)
@@ -850,18 +854,24 @@ func compareStructType(a, b reflect.Type) map[string]int {

        for i := 0; i < len(aFields) || i < len(bFields); i++ {
                if i < len(aFields) {
-                       c := matchings[aFields[i].Name]
-                       matchings[aFields[i].Name] = c + 1
+                       name := matchName(aFields[i])
+                       c := matchings[name]
+                       matchings[name] = c + 1
                }
                if i < len(bFields) {
-                       c := matchings[bFields[i].Name]
-                       matchings[bFields[i].Name] = c + 2
+                       name := matchName(bFields[i])
+                       c := matchings[name]
+                       matchings[name] = c + 2
                }
        }

        return matchings
 }

+func matchName(field reflect.StructField) string {
+       return field.Name + "-" + field.Type.String()
+}
+
 func enumFields(v reflect.Type) []reflect.StructField {
        fields := []reflect.StructField{}
```

**Comment by fsouza** [comment]
Hey @jasdel, thanks for the feedback. I implemented those fixes and ``TestUploadInputS3PutObjectInputPairity`` is passing locally, but when I try to run all package tests I get a panic and the test suite aborts:

```
% go test
--- FAIL: TestUploadOrderMultiDifferentPartSize (0.04s)
panic: interface conversion: io.SectionReader is not io.Reader: missing method Read [recovered]
	panic: interface conversion: io.SectionReader is not io.Reader: missing method Read

goroutine 227 [running]:
testing.tRunner.func1(0xc42101c780)
	/Users/fsouza/.gimme/versions/go/src/testing/testing.go:742 +0x291
panic(0x141a600, 0xc42117bec0)
	/Users/fsouza/.gimme/versions/go/src/runtime/panic.go:502 +0x229
github.com/aws/aws-sdk-go-v2/service/s3/s3manager_test.buflen(0x1459c00, 0xc420183740, 0x14b789a)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload_test.go:96 +0x41
github.com/aws/aws-sdk-go-v2/service/s3/s3manager_test.TestUploadOrderMultiDifferentPartSize(0xc42101c780)
	/Users/fsouza/src/github.com/aws/aws-sdk-go-v2/service/s3/s3manager/upload_test.go:209 +0x437
testing.tRunner(0xc42101c780, 0x14d3018)
	/Users/fsouza/.gimme/versions/go/src/testing/testing.go:777 +0xc4
created by testing.(*T).Run
	/Users/fsouza/.gimme/versions/go/src/testing/testing.go:824 +0x2ca
exit status 2
FAIL	github.com/aws/aws-sdk-go-v2/service/s3/s3manager	1.782s
```

Do you see that in your environment too? It looks like the code is trying to use an io.SectionReader (not *io.SectionReader) as an io.Reader.

**Comment by jasdel** [comment]
@fsouza hmm, I'm not running into that issue. Can you verify that you're pr is based of tip of the SDK?

**Comment by fsouza** [comment]
@jasdel yeah, with latest master :(

I created this Dockerfile to show how to reproduce the issue: https://gist.github.com/fsouza/d0b6374b972dd3041b9d99de9db1fb9f

The test also fails without applying the patch. It's weird x)

**Comment by xibz** [comment]
@fsouza - Looks like one of our dependencies broke. I'll go ahead and take a look into this.

**Comment by jasdel** [comment]
@fsouza one workaround for this issue to update your Go workspace so that github.com/jmespath/go-jmespath is on [0.2.2](https://github.com/jmespath/go-jmespath/releases/tag/0.2.2).

With git directly you can do:

```sh
cd $(go env GOPATH)/src/github.com/jmespath/go-jmespath
git checkout 0.2.2
```

**Comment by fsouza** [comment]
@jasdel thanks for the info, I'm using dep in the application. I checked out that version of go-jmespath locally and the tests are now passing:

```
% go test
PASS
ok  	github.com/aws/aws-sdk-go-v2/service/s3/s3manager	2.320s
```

I think this PR is good for review now! :D

**Comment by jasdel** [comment]
Thanks for taking the time to put this PR together, and adding the test. The change looks good.

**Pull request merged**
